language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- nvm install node
- yarn install
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rails webpacker:compile
- bundle exec rspec
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: BlSpTRvgNMupQ2CoeEYJtbG0NQLpM74h+NIhBAjkFlzJiG14Rj0Uhpny4M/txWCpNdDqNKOwWxw08m5DJjLZCUofd/1994UXAc6Ool39Dj3AZ3q5JaveyEF01dENPSZ4/YcB7Peg41ADY0OuzZF0Mk2LFbgWtIjE4afbKBkaTzjzBOI6HovLv/HLiZvBho2GsPDDdE3GM4pBdsFIka3C/gxC2Ry90HpmpHKcsnHYvZH4dIjIsD80WTNyGkPskTjZE3d+e6L59H0zPkMveueRwOYYMnM9Q8WsD7xfKfj+/WMetylj25Qa9QFb+QofqrV3662+Cv0LzLyO2XL9VporkMMyPzNvH12dKxS9HGI+kgrSjvy9d9OPtqxO+7VOuQf63hx1OE+C1UyfyXdci5bLnb5I06dUDNdMiu1oo+OE5TPjneeaJpW3XMiWswSWK6IXDVftQpTAfJt0QiWF8peHNrV89t8YbAfm6hteZ5yQcWljSL7CZtH68dNJYVUvo+jDX9y/qctL51mxVK/h/39zF5zp7trC4H62x+PWIw3zcL6i2nazWRRpoTAjqx52UPYrUU5zZ6FVEP0Ggyq+Q8RTV5GPDbtwzL7kEHVh96xm6sfqvpc00AVi/Pi0vNjwyKVr99SaAevzpKd0H/zBGqpn7RqT4roMUejwmVvkq/Cu++M=
  secret_access_key:
    secure: Hn55I0Xx1W08Inn5mVUByrc3I3Pls83IAP18l3P0WLuzCabsbxAWGT2iNUWoFtTMR3Wao//TjOdtu9ANJHFFneqQRec9UEQtm8c2be8tMJC9jLVsSk0iG2mKmdzqlOSXASPFXiJ82i2FirUx1CFCXABlbIL2q9pd4eussN7NUYTH15boDbiTA05UPDJZ595wx5qiZk5E+BRbHZC5WwildoxBpoOXIIdH26fmPCS+sG4AaFHvYzvn2mtKwRnx15i7b2c5b90VOkpP18SHCaMHULqE5DzWYafx7CRYxyMxaI7rJRBZCJzolm3hmcgphl8khqofFX0f2BKoQgnWbuyKTuwn38o70B2b7XcErjnBz4U7EXEzUooWkJQkN0czJGYGmNFLYpPQKQOw5gcOAo3h0DISmN+SB/1TQLSp6Uk+S6buEjAB210sYlDLgvWjb8qdfdGnVmUOuedNznMuwLNoTaujwiLdEt3XtQgCmfiQVXVeZijnXeCDVlDLOmmr7+iHKBdKKmCwQgwsoRF/xOALXYrpA7G53jDgnDsAcwo84VhqQ3F9jadKxXeexgpcqtO1VWV8v1ut3ao2kuXGRZt00+azcqztBAy7MEWDdQW3Effe1Yc80olPeRI6SDzpk2atNnbY+N+t0FRM8o6Z6PexRe08FOHKDYdoc+ARbG12gv4=
  region: us-east-2
  app: viewing party
  env: Viewingparty-env
  bucket: elasticbeanstalk-us-east-2-036883958305
  run: rails db:migrate
  on:
    branch: travis
