language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  - provider: elasticbeanstalk
    access_key_id:
      secure: "k9PbKWgWfDWQRBH2wnLLdK8yFFyJAFQWWGKMjXaz4jgqF5EVVfzNcUUEEXIbVDeTq1o/zN5Isd7tIh37Mxw7eyJWzMzyLBNC6Q9obNT0y4kC4t4H8/gawuT5g6CKPbM6N3ruFU5iVYDngncP/yP/Ig0InmVMN9/npZlAfq69rGC/qXQPTptj2gHY3L4eDWxHPKp9SvoFXzcq0NlumZwHmmE0XuCLSZFQzEn+V1rtFT3nNqZcgDK77jFwBoA4L5bFZkL8E6W0unOkZWVrJ+882sXUoCCA+FGP5nr6rtT63+e12xhwySfa478uyVaWah9NErVotqPTzk/o5t1xdJf0eehCI7mWljM/HL+2pzosZAEe8w2RiducT0xjbSyXb1d/9bpV8oI99RP4bX/HidpkW0fwyAi8/+yaFNuV2Jc9CzqmMklNKgnsx5vSriPTf84+TgeGUxxRF63LO39Sm0gBHDXAq2O3099vNeqO5Br4oZECT8dL5a7PuDYSoSS+Ry/jU00sP/3kekvuZtMqFmQZkYSSJut7MyG7Zyx9PaYwefxtf7PZR3jshpsSqthUhdNmFKY0D8CerylvNhVaxYVdLVzkILIt7RSTH89Wv+ZcrgXQMDLsC6K87fRFIwn9ZYCybnIMLJl1IDn8XqgFNK+vSXOPcj3SrQKL4Se8ihKrU5M="
    secret_access_key:
      secure: "lE9sZnxtoiXlgQaxNv3pmDgFsPK6s/pI43XU+CBimFBDuZoNIu7gboqervChkqdJhEYj+ZSKLnBcfYgd6VPV+BR/FqxSlDT2Q72gF5VseshslrrXQzNwbjnz4QUJC/hoSmIGZD3F9PJPas0o5dHDaw7IWOErjIBdFs057IVjBlbCrzGdbyMa1R5zxZWcD05f/91oQDKNnwEk1rzLN/7bbbemtmIWHt/DThZXNAxvBHZuhpm8AFDaTSJQeU7sNB3wPccLMwSEyOymfqpIh/6RwrywqVHO/8e5cr+OFs0y7TX1LoOjk87w3xPixB2f2oZ7xi2aeK9i0KFDomfxF54b7YVOj95zoC10NV8ADQQnz2fVj/43SdQWCeTET70cHMsO3UvIfcwsy8G/q+YTW/cR8nkJM9oDSTGlJui6ge1fcIZ/8VNYhqM2WosiwIyLceU2MMFM/ozAF7FSBVLPp2RSfkTrFt6zrUVSmMuZ0U60yRer0N7k6ZPqjku+oLkfPESFe1sWHG/efy3pXNgkGnS6bYzIcUbOjb34sOSsR0qVWnwI/UWJKZZtpE/nZYfSrlIMnmtE0geSch2CjOkFxYPMYBdSISQt+9iwFxVGxj5U7F768vEkUwNMsJ0N/YzOh2j4bqWMrxIvdNzrYZSz7aBlzNnlCMTiQxO5MSgHrQovhP0="
    region: "us-east-2"
    app: "viewing party"
    env: "Viewingparty-env"
    bucket: "elasticbeanstalk-us-east-2-036883958305"
    run: rails db:migrate
    on:
      branch: travis
#  - provider: "heroku"
#     api_key:
#     app:
#     run: rails db:migrate
