language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rails webpacker:install
- bundle exec rspec
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: RisqronN9JZSqlWPrqKT3VUZdgie8VrvmJXIIoGwPVNkFxeUu8oAdwe3NGu74n91crQahgodfj5rCTXWmPkvqUrq82om73n74t9O5pYnGhIbrZqC3xUG9lzE7/Hb5HSMu6dH5cGCKFqWr0M8UnjdNLdD2xauikFd9cyoO/LJkHaq9u+8YB4znw4QZAiScZE3G9xiFNwd6smS73n88aheH86zWhoMzgRwUj0YGOp7ruWJM1D9QdTxy90yD1TR3lXdS3NNDySzzhtz8PEopOuwuL2KWb4Qj58xNXsBVSTLX97+eOuFeVYjGSzHFcOnmDBP1WGk1AWfsFbOuivB3ivr5BKF0MYflTxFC+jjX1XAlLAxxVL6s0tg/klX6FRFp8t0WZZu6oIIy4Wh5tiARUHUNIKyTLkbHKxG4ZsfGSSXXNfmtHLkNM8gb2U/IoBUXvZVzSBNEsA4TnnamfWIA6n5YLITDILQXImNxM8fCWZ0FaPLy+lgu7iZoKKBGhgHW041NBeenRw6Z/almEXeyg35F53/kflWiiDII2vcDE6ONMCd+ldqHmf7libTJP4sbmFik6GR7UYH4go9ix8JT10rXMAaFMTSXJIekdrCYbf0IT6Tw8T7m/o4VpHuuwYBgGTXPig3wuK48N4fgxwwR9g/wbj5pqj6OgLk5XbFLZ7PXQc=
  secret_access_key:
    secure: drBeeSs522PBfJ0ToJzP2M31Fj1kpLzPXkAMMFeW/ka2x79m+xrh8gsPa1/JOls3O6WVT0eUj4OWAGmWy34V0L5NJmIGsbqq4mCI8iTD2O/Ue2YAWz1e+LKTiY+VhKZItcNQa7bp7xSr1e0W3pax0xg7SlZaHhgkB2kcp/mS3f7j7GH79+Z6/YOqGYSQDmdy1oaMWlskwr60+vY9Yqi2EnzGoyXSWnIBED/Bmp71w7ADPhzyDLNRpbzb1kWkQ/4qtlQMfZYmxFFCNwwpxnsEuKHfJ5e0sxvznXpftq1nD1Bs8fcpd7b+cYgpon9VXPGsBdhvfqO0OBvLhOzsmiit6cfVKOGadEVMBEvvIVG8ROIhWAf16y9ykRu47+fOtzSGIo3kqp5pcv/U+hOyhFhKX0TXkLQRvjBN1BOlIoAgrv4XxKY3vyvMzIlzngjA9INzjBxDWd48ZxNKr49+ylpONNOvevgGk9Vg+KuZi85gRXQwtjaxtWs6jAmRiHIsjrmDMZTyKccmfTs06mBE9ia7vpMDeQbgkM7e9aGMj6MCyqQWzNivyJlThhvjd4Qy8L0+eboqM0KcaKhbqxT5wR6to6eZ2ziljPeGm8xGX7XwpwfyVFLseUfjdPaui12kLMJvuxLDzg2CRKN6wJkVrgNv6Hq/UZ21Zmr8drCKBZq/uYU=
  region: us-east-2
  app: viewing party
  env: Viewingparty-env
  bucket: elasticbeanstalk-us-east-2-036883958305
  run: rails db:migrate
  on:
    branch: travis
